version: 2
jobs:
  # TODO: add caching
  python:
    docker:
      - image: themattrix/tox
    environment:
      TEST_RESULTS_DIR=results/
    steps:
      - checkout
      - run:
          command: pip install tox
          name: Install Tox
      - run: mkdir results
      - run:
          command: tox
          name: Run Tox Tests
      - store_test_results:
          path: results


workflows:
  version: 2
  UnitTests:
    jobs:
      - python
